name: docker
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: echo ${DOCKERHUB_TOKEN} | docker login --username agilenatives --password-stdin
      env:
        DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

    - run: docker build amazon --file amazon/Dockerfile --tag agilenatives/release:amazon
    - run: docker push agilenatives/release:amazon

    - run: docker build . --file Dockerfile --tag agilenatives/release:latest
    - run: docker push agilenatives/release:latest

    - run: docker build azure --file azure/Dockerfile --tag agilenatives/release:azure
    - run: docker push agilenatives/release:azure

    - run: docker build hetzner --file hetzner/Dockerfile --tag agilenatives/release:hetzner
    - run: docker push agilenatives/release:hetzner

    - run: docker build digitalocean --file digitalocean/Dockerfile --tag agilenatives/release:digitalocean
    - run: docker push agilenatives/release:digitalocean
